spring:
  datasource:
    #使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: wl-travel

# 自定义的主数据源配置信息
primary:
  datasource:
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driverClassName: com.mysql.cj.jdbc.Driver
      #配置基本属性
      url: jdbc:mysql://rm-bp128giq0k0b9zi23qo.mysql.rds.aliyuncs.com:3306/test_groot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: groot
      password: Ilovebenz5e
      #配置初始化大小/最小/最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000

server:
  port: 8080
  servlet:
    context-path: /travel

